from tkinter import * 
root =Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
root.title("Welcome Page")
img=PhotoImage(file='.vscode\Project\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=0,columnspan=7)
Label(root,text="Online Bus Booking System",font='Times 40 bold',fg='yellow',bg='red').grid(row=1,column=0,pady=15,padx=w//3,columnspan=7)
Label(root,text="Enter Journey Details",font="Arial 28",fg='yellow',bg='red').grid(row=2,column=0,columnspan=7)
e1=Entry(root)
e1.grid(row=3,column=1)
e2=Entry(root)
e2.grid(row=3,column=2)
e3=Entry(root)
e3.grid(row=3,column=3)
Label(root,text='To',font='Cosmic 11').grid(row=3,column=0,columnspan=2)
Label(root,text='From',font='Cosmic 11').grid(row=3,column=1,columnspan=2)
Label(root,text='Journey Date',font='Cosmic 11').grid(row=3,column=2,columnspan=2)
Button(root,text='Show Bus',fg='yellow',bg='red',font='Times 12').grid(row=3,column=4)
img1=PhotoImage(file='.vscode\Project\home.png')
Label(root,image=img1).grid(row=3,column=5)
root.mainloop()
