
from tkinter import *
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img=PhotoImage(file='.vscode\Project\Bus_for_project.png')
Label(root,image=img).grid(row=0,column=0,columnspan=7)
img1=PhotoImage(file='.vscode\Project\home.png')
Label(root,image=img1).grid(row=4,column=6,columnspan=2,pady=20)
Label(root,text='Online Bus Booking System',font='Cosmic 15 bold',fg='yellow',bg='red').grid(row=1,column=0,pady=10,padx=w//3,columnspan=7)
Label(root,text='Add Bus Operator Details',font='Cosmic 14',fg='yellow',bg='Red').grid(row=2,column=0,columnspan=7)
a1=Entry(root)
a1.grid(row=3,column=1)
a2=Entry(root)
a2.grid(row=3,column=2)
a3=Entry(root)
a3.grid(row=3,column=3)
a4=Entry(root)
a4.grid(row=3,column=4)
a5=Entry(root)
a5.grid(row=3,column=5)
Label(root,text='Operator Id',font='Times 15 bold',fg='yellow',bg='red').grid(row=3,column=0,columnspan=1)
Label(root,text='Name',font='Times 15 bold',fg='yellow',bg='red').grid(row=3,column=1,columnspan=2)
Label(root,text='Address',font='Times 15 bold',fg='yellow',bg='red').grid(row=3,column=2,columnspan=2)
Label(root,text='Phone',font='Times 15 bold',fg='yellow',bg='red').grid(row=3,column=3,columnspan=2)
Label(root,text='Email',font='Times 15 bold',fg='yellow',bg='red').grid(row=3,column=4,columnspan=2)
Button(root,text='Add',font='Times 15 bold',bg='yellow',fg='red').grid(row=3,column=6,columnspan=2)
Button(root,text='Edit',font='Times 15 bold',bg='yellow',fg='red').grid(row=3,column=8,columnspan=2)
root.mainloop()