from tkinter import *
root=Tk()
root.geometry('800x800')
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img11=PhotoImage(file='.vscode\Project\Bus_for_project.png')
Label(root,image=img11).grid(row=0,column=0,columnspan=7)
img111=PhotoImage(file='.vscode\Project\home.png')
Label(root,image=img111,bg='yellow').grid(row=5,column=4,columnspan=2,pady=60)
Label(root,text='Online Bus Booking System',font='Cosmic 14',fg='yellow',bg='Red').grid(row=1,column=0,pady=20,padx=w//3,columnspan=7)
Label(root,text='Add Bus Operator Details',font='Cosmic 14',fg='yellow',bg='Red').grid(row=2,column=0,columnspan=7)
e16=Entry(root)
e16.grid(row=3,column=1)
e17=Entry(root)
e17.grid(row=3,column=3)
e18=Entry(root)
e18.grid(row=3,column=4)
e19=Entry(root)
e19.grid(row=3,column=5)
e20=Entry(root)
e20.grid(row=3,column=6)
Label(root,text='Bus Id',font='Helvetica 13').grid(row=3,column=0,columnspan=2)
Label(root,text='Bus Type',font='Helvetica 13').grid(row=3,column=1,columnspan=2)
Label(root,text='Capacity',font='Helvetica 13').grid(row=3,column=2,columnspan=2)
Label(root,text='Fare Rs',font='Helvetica 13').grid(row=3,column=3,columnspan=2)
Label(root,text='Operator Id',font='Helvetica 13').grid(row=3,column=4,columnspan=2)
Label(root,text='Route Id',font='Helvetica 13').grid(row=3,column=5,columnspan=2)
Button(root,text='Add Bus',font='Cosmic 14',fg='yellow',bg='Red').grid(row=5,column=2,columnspan=2)
Button(root,text='Edit Bus',font='Cosmic 14',fg='yellow',bg='Red').grid(row=5,column=3,columnspan=2)
Bus_Type=StringVar(root,'Bus Type')
option=['2x2','3x2','Ac 2x2','Ac 3x2']
d_menu=OptionMenu(root,Bus_Type,*option)
d_menu.grid(row=3,column=2)
root.mainloop()