from tkinter import *
root=Tk()
root.geometry('800x800')
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img11=PhotoImage(file='.vscode\Project\Bus_for_project.png')
Label(root,image=img11).grid(row=0,column=0,columnspan=7)
img111=PhotoImage(file='.vscode\Project\home.png')
Label(root,image=img111,bg='yellow').grid(row=5,column=4,columnspan=2,pady=60)
Label(root,text='Online Bus Booking System',font='Cosmic 14',fg='yellow',bg='Red').grid(row=1,column=0,pady=20,padx=w//3,columnspan=7)
Label(root,text='Add Bus Operator Details',font='Cosmic 14',fg='yellow',bg='Red').grid(row=2,column=0,columnspan=7)
e10=Entry(root)
e10.grid(row=3,column=1)
e11=Entry(root)
e11.grid(row=3,column=2)
e12=Entry(root)
e12.grid(row=3,column=3)
Label(root,text='Route Id',font='Helvetica 13').grid(row=3,column=0,columnspan=2)
Label(root,text='Station Name',font='Helvetica 13').grid(row=3,column=1,columnspan=2)
Label(root,text='Station Id',font='Helvetica 13').grid(row=3,column=2,columnspan=2)
Button(root,text='Add Route',font='Cosmic 14',fg='yellow',bg='Red').grid(row=3,column=4,columnspan=2)
Button(root,text='Delete Route',font='Cosmic 14 bold',fg='yellow',bg='Red').grid(row=3,column=6,columnspan=2)
root.mainloop()